<table>
<tr>
<td width=15%><img src="https://www.nitrkl.ac.in/assets/images/logo.png"></img></td>
<td><center><h1>National Institute of Technology
Rourkela, Odisha, India, 769008</h1><h2>Department of Computer Science Engineering</h2></center></td>
</tr>
<tr><td colspan=2><center><h3>SUMMER INTERNSHIP cum TRAINNING PROGRAMME</h3></br>
            <b>(STTP: Introduction to Data Science using Python)</b></center></td></tr>
</table>

_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [4]:
#Code here
import numpy as np
arr = np.array([10,5,7,20,15,-9,33])
print(arr)


[10  5  7 20 15 -9 33]


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [5]:
#Code here
import numpy as np
arr = np.array([10,5,7,20,15,-9,33])
print(arr)
max_num = arr[0]
min_num = arr[0]
for i in arr[1:]:
    if max_num<i:
        max_num=i
    else:
        min_num=i
print(max_num,min_num)

[10  5  7 20 15 -9 33]
33 -9


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [14]:
#Code here
import numpy as np
matrix1=np.array([[1,2] ,[3,4]])
matrix2=np.array([[5,6],[7,8]])
sum_result= matrix1 + matrix2
print("\nsum of the result:")
print(sum_result)
sub_result= matrix1 - matrix2
print('\nsubstraction of result is :')
print(sub_result)



sum of the result:
[[ 6  8]
 [10 12]]

substraction of result is :
[[-4 -4]
 [-4 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [4]:
#Code here
!pip install numpy                   

'pip' is not recognized as an internal or external command,
operable program or batch file.


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [1]:
#Code here
import numpy as np
random_matrix= np.random.randint(1,11,size=(5,6))
print(random_matrix)


ModuleNotFoundError: No module named 'numpy'

___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [ ]:
#Code here


### Great Job!