<table>
<tr>
<td width=15%><img src="https://www.nitrkl.ac.in/assets/images/logo.png"></img></td>
<td><center><h1>National Institute of Technology
Rourkela, Odisha, India, 769008</h1><h2>Department of Computer Science Engineering</h2></center></td>
</tr>
<tr><td colspan=2><center><h3>SUMMER INTERNSHIP cum TRAINNING PROGRAMME</h3></br>
            <b>(STTP: Introduction to Data Science using Python)</b></center></td></tr>
</table>

_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [1]:
import numpy as np

# Create the array
arr = np.array([10, 5, 7, 20, 15, -9, 33])

# Print the array
print("Array:", arr)

# Find the maximum and minimum values
max_value = np.max(arr)
min_value = np.min(arr)

# Print the maximum and minimum values
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Array: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [7]:
import numpy as np

def find_max(arr):
    if len(arr) == 0:
        return None
    
    max_value = arr[0]  # Assume the first element is the maximum
    
    for element in arr[1:]:
        if element > max_value:
            max_value = element
    
    return max_value

# Accepting array of elements from the user
arr = np.array(input("Enter elements of the array separated by spaces: ").split(), dtype=int)

# Finding the maximum value
max_value = find_max(arr)

if max_value is not None:
    print("Maximum value:", max_value)
else:
    print("Array is empty")

Enter elements of the array separated by spaces:  1 2 22 3 44 5 -10


Maximum value: 44


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [3]:
import numpy as np

# Define the matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 4], [6, 8]])

# Find the sum of matrices
sum_result = matrix1 + matrix2
print("Sum of the matrices:")
print(sum_result)

# Find the subtraction of matrices
subtraction_result = matrix1 - matrix2
print("\nSubtraction of the matrices:")
print(subtraction_result)


Sum of the matrices:
[[ 3  6]
 [ 9 12]]

Subtraction of the matrices:
[[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [4]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.rand(5, 6)
print("Random Matrix:")
print(random_matrix)

# Add another row with random elements
new_row = np.random.rand(1, 6)
random_matrix = np.vstack([random_matrix, new_row])
print("\nMatrix with added row:")
print(random_matrix)

# Find the sum of each row
row_sums = np.sum(random_matrix, axis=1)
print("\nSum of each row:")
print(row_sums)

Random Matrix:
[[0.40505468 0.05375485 0.99067976 0.48182283 0.55261661 0.58658176]
 [0.63906356 0.34296428 0.15585825 0.42401167 0.27753739 0.66308744]
 [0.37900516 0.38067069 0.50519536 0.75461705 0.33361185 0.07902437]
 [0.22768548 0.18586809 0.11487275 0.29087698 0.97452849 0.78266317]
 [0.57177619 0.381039   0.59924039 0.72757484 0.7915899  0.40078135]]

Matrix with added row:
[[0.40505468 0.05375485 0.99067976 0.48182283 0.55261661 0.58658176]
 [0.63906356 0.34296428 0.15585825 0.42401167 0.27753739 0.66308744]
 [0.37900516 0.38067069 0.50519536 0.75461705 0.33361185 0.07902437]
 [0.22768548 0.18586809 0.11487275 0.29087698 0.97452849 0.78266317]
 [0.57177619 0.381039   0.59924039 0.72757484 0.7915899  0.40078135]
 [0.23705674 0.8228047  0.03452573 0.17747181 0.4737864  0.31391185]]

Sum of each row:
[3.07051049 2.50252259 2.43212449 2.57649495 3.47200167 2.05955722]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [5]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.randint(0, 10, size=(5, 6))
print("Random Matrix:")
print(random_matrix)

# Add another column with random elements
new_column = np.random.randint(0, 10, size=(5, 1))
random_matrix = np.hstack([random_matrix, new_column])
print("\nMatrix with added column:")
print(random_matrix)

# Compute the sine of each element
sin_matrix = np.sin(random_matrix)
print("\nSine of each element:")
print(sin_matrix)

Random Matrix:
[[9 0 5 2 8 9]
 [9 2 5 7 0 2]
 [1 4 6 5 5 5]
 [5 1 7 0 3 0]
 [7 7 8 4 6 9]]

Matrix with added column:
[[9 0 5 2 8 9 5]
 [9 2 5 7 0 2 5]
 [1 4 6 5 5 5 1]
 [5 1 7 0 3 0 4]
 [7 7 8 4 6 9 5]]

Sine of each element:
[[ 0.41211849  0.         -0.95892427  0.90929743  0.98935825  0.41211849
  -0.95892427]
 [ 0.41211849  0.90929743 -0.95892427  0.6569866   0.          0.90929743
  -0.95892427]
 [ 0.84147098 -0.7568025  -0.2794155  -0.95892427 -0.95892427 -0.95892427
   0.84147098]
 [-0.95892427  0.84147098  0.6569866   0.          0.14112001  0.
  -0.7568025 ]
 [ 0.6569866   0.6569866   0.98935825 -0.7568025  -0.2794155   0.41211849
  -0.95892427]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [6]:
import numpy as np

# Generate a random matrix of size 5x6
random_matrix = np.random.randint(0, 10, size=(5, 6))
print("Random Matrix:")
print(random_matrix)

# Extract the specified rows and columns using slicing
resultant_matrix = random_matrix[2:4, 1:4]
print("\nResultant Matrix:")
print(resultant_matrix)

Random Matrix:
[[7 4 6 2 4 6]
 [1 3 9 5 9 3]
 [8 8 1 4 2 9]
 [9 4 0 4 8 9]
 [0 7 5 7 3 5]]

Resultant Matrix:
[[8 1 4]
 [4 0 4]]


### Great Job!